<a href="https://colab.research.google.com/github/soyab266/data-science/blob/master/back_propogation_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [8]:
df=pd.DataFrame([[1,2,0],[3,6,1],[4,8,1],[5,8,0]], columns=['age', 'score','placement'])

In [9]:
df.head(2)

age  score  placement
0    1      2          0
1    3      6          1

In [11]:
model=Sequential()
model.add(Dense( 2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 6         
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.get_weights()

[array([[-0.59935737,  0.10053885],
        [-1.010697  ,  0.55229044]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.131127 ],
        [ 0.6170875]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
optimizer=keras.optimizers.Adam(learning_rate=0.01)
model.compile( loss='binary_crossentropy', optimizer=optimizer)

In [26]:
model.fit(df.iloc[:,0:-1].values,df['placement'].values, epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 1s 6ms/step - loss: 0.7195
Epoch 2/50
4/4 [==============================] - 0s 5ms/step - loss: 0.7114
Epoch 3/50
4/4 [==============================] - 0s 4ms/step - loss: 0.7043
Epoch 4/50
4/4 [==============================] - 0s 6ms/step - loss: 0.7004
Epoch 5/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6957
Epoch 6/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6978
Epoch 7/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6902
Epoch 8/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6840
Epoch 9/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6799
Epoch 10/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6767
Epoch 11/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6746
Epoch 12/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6684
Epoch 13/50
4/4 [==============================] - 0s 4ms/step - loss: 0.