<a href="https://colab.research.google.com/github/soyab266/data-science/blob/master/back_propogation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [10]:
df=pd.DataFrame([[1,2,3], [2,4,9],[6,8,7], [2,5,9]], columns=['cgpa', 'score', 'lpa'])

In [12]:
df.head(4)

cgpa  score  lpa
0     1      2    3
1     2      4    9
2     6      8    7
3     2      5    9

In [15]:
model=Sequential()

In [16]:
model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.get_weights()

[array([[-1.2050838 , -0.60015655],
        [-0.14528584, -1.1779586 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9492984 ],
        [ 0.97601616]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
from keras.utils.sidecar_evaluator import optimizer
optimizer=keras.optimizers.Adam(learning_rate=0.01)
model.compile( loss='mean_squared_error',optimizer=optimizer)

In [35]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=400, verbose=1,batch_size=1)

Epoch 1/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5466
Epoch 2/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5137
Epoch 3/400
4/4 [==============================] - 0s 3ms/step - loss: 1.6354
Epoch 4/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5347
Epoch 5/400
4/4 [==============================] - 0s 4ms/step - loss: 1.5380
Epoch 6/400
4/4 [==============================] - 0s 4ms/step - loss: 1.5114
Epoch 7/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5321
Epoch 8/400
4/4 [==============================] - 0s 4ms/step - loss: 1.5345
Epoch 9/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5062
Epoch 10/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5326
Epoch 11/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5643
Epoch 12/400
4/4 [==============================] - 0s 3ms/step - loss: 1.5261
Epoch 13/400
4/4 [==============================] - 0s 3ms/st

In [36]:
model.get_weights()

[array([[ 0.17223619, -2.0152361 ],
        [-1.6061351 ,  0.46827087]], dtype=float32),
 array([-0.2786409 ,  0.12020724], dtype=float32),
 array([[-1.46518  ],
        [ 1.3000956]], dtype=float32),
 array([0.35793242], dtype=float32)]