<a href="https://colab.research.google.com/github/soyab266/data-science/blob/master/multiple_linear_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from numpy.random import test
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [3]:
x

array([[ 9.29818420e-01, -1.33647807e+00],
       [-5.69079987e-01,  3.98485278e-01],
       [-1.44815712e+00,  8.73172539e-01],
       [-1.44007482e+00,  2.35758883e-01],
       [-2.81228755e-01,  1.04605596e+00],
       [ 1.54623602e-02, -1.92889467e+00],
       [ 1.48978701e+00,  1.27757464e+00],
       [-9.04849545e-02, -4.22190006e-02],
       [ 7.25146533e-01, -4.53045314e-01],
       [-9.98835054e-01, -7.39438252e-01],
       [-5.86553756e-01, -1.20244609e+00],
       [ 5.93568579e-01,  3.50858851e-01],
       [ 5.28765499e-01, -6.25404614e-01],
       [ 1.06261535e+00,  1.41514892e+00],
       [ 5.25284211e-02, -8.01406020e-02],
       [-2.11648502e+00, -2.84754111e-01],
       [ 9.52573180e-01,  1.34432498e+00],
       [ 7.72942686e-01, -1.21098985e+00],
       [-8.91112367e-01, -2.40639290e-01],
       [-8.06864301e-01, -4.73159522e-02],
       [ 2.52331101e-01, -1.88386383e+00],
       [ 1.67739437e+00,  7.55678397e-01],
       [ 9.51899253e-04, -1.01129514e+00],
       [ 2.

In [4]:
y

array([ -35.3530342 ,  -89.15160076, -106.79750112,  -59.38915762,
         50.77146859,  -17.47055671,   63.860656  ,   21.24276383,
        -33.59084827, -114.2329867 ,   -0.91749859,   51.39649931,
         27.36734473,   34.98137656,  -70.65662192, -121.14204931,
         40.19338194,    1.07534264, -147.60686251, -106.44716112,
         -4.93872602,   -1.095023  ,   47.11398626,   49.61246582,
         -8.85324008,  -75.1383954 ,  -55.52302913,  -11.64416681,
        -26.15814753,   10.75570834,   -0.25385749,  -24.33028321,
          0.93675664,   56.47957134,   27.81771223,   10.16040716,
         30.40280709,  -75.72303624,   41.80877526,   42.2032222 ,
          6.56979572,  -51.34431243,  -14.67753724,  -54.45690542,
        -27.18928505,   54.9668485 ,  -41.00344614,   70.85581609,
         10.36536927,   24.29111275,  -12.81370683, -132.2560374 ,
         84.36150877,   14.76967942,    3.02364235,   76.62121909,
        -11.16311778,  -41.3932583 ,  -92.45392819,   42.33042

In [5]:
df=pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})

In [6]:
df.head()

feature1  feature2      target
0  0.929818 -1.336478  -35.353034
1 -0.569080  0.398485  -89.151601
2 -1.448157  0.873173 -106.797501
3 -1.440075  0.235759  -59.389158
4 -0.281229  1.046056   50.771469

In [7]:
df.shape

(100, 3)

In [12]:
px.scatter_3d(df,x='feature1',y='feature2',z='target')

In [22]:
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [23]:
lr=LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [24]:
y_pred=lr.predict(x_test)

In [25]:
mean_absolute_error(y_test,y_pred)

36.06348747823666

In [26]:
mean_squared_error(y_test,y_pred)

2257.699045939009

In [27]:
r2_score(y_test,y_pred)

0.4054800305732428

In [53]:
lr.coef_

array([34.72157795, 14.17367806])

In [54]:
lr.intercept_

-1.6465149027062147